name: Export unpack and commit the solution
run-name: Getting ${{ github.event.inputs.solution_name }} solution from environment ${{ github.event.inputs.environment_url }} environment and committing
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: yoursolutionname
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://[your-env].crm.dynamics.com"
env:
#edit your values here
  TENANT_ID: '67266d43-8de7-494d-9ed8-3d1bd3b3a764'
  CLIENT_ID: '4880a9e8-fd3c-4b89-9966-dc59b1e09984'
permissions:
  contents: write
jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - if: ${{ false }} # this will never run, but will force powerplatform-actions to download
        name: Who Am I
        uses: microsoft/powerplatform-actions/who-am-i@latest
        with:
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
          tenant-id: ${{env.TENANT_ID}}
          environment-url: ${{ github.event.inputs.environment_url}}

      # We need to use pac directly.
      # So we set the path to pac that ships with the Actions
     
      - name: Create Branch
        run: |
          git checkout -b "newSolutionBranch"
          
      # Runs a set of commands using the runners shell
      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: ${{ github.event.inputs.environment_url}}
            app-id: ${{ env.CLIENT_ID }}
            client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
            tenant-id: ${{env.TENANT_ID}}
            solution-name: ${{ github.event.inputs.solution_name }}
            solution-output-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
            overwrite: true
            managed: true

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
          solution-folder: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}
          solution-type: 'Managed'
          process-canvas-apps: true
          overwrite-files: true

      - name: commit changes
        shell: pwsh
        run: |

          git config --global user.email "actions@samler.cz"
          git config --global user.name "Github Actions Bot"

          git add .
          git commit -m "Commiting exported solution"
          git push
