name: deploy-package-to-environment


on:
  workflow_dispatch:
    inputs:
      environment-url:
        description: 'Environment url to deploy to'
        required: true
        default: 'XXX.crm4.dynamics.com'
env:
#edit your values here
  TENANT_ID: '67266d43-8de7-494d-9ed8-3d1bd3b3a764'
  CLIENT_ID: '4880a9e8-fd3c-4b89-9966-dc59b1e09984'
permissions:
  contents: write
jobs:
  build-and-publish-solution:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore MyVisualStudioSolution.sln

    - name: Build
      run: dotnet build MyVisualStudioSolution.sln

    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: D:\a\PowerPlatformGithubActions\PowerPlatformGithubActions\src\MyDataverseSolution\bin\Debug\*.zip
  
    - name: dotnet Publish
      run: dotnet publish D:\a\PowerPlatformGithubActions\PowerPlatformGithubActions\src\Packages\MyDataversePackage\MyDataversePackage.csproj

    - name: Publish packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: D:\a\PowerPlatformGithubActions\PowerPlatformGithubActions\src\Packages\MyDataversePackage\bin\Debug\*.zip

  deploy-package-to-environment:
    needs: build-and-publish-solution
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest

    steps:
    - name: Install Power Platform Tools    
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ github.event.inputs.environment-url }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: packages

    - name: Debug
      run: ls -r

    - name: Deploy Package
      uses: microsoft/powerplatform-actions/deploy-package@v1
      with:
        environment-url: ${{ github.event.inputs.environment-url }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
        tenant-id: ${{env.TENANT_ID}}
        package: 'D:\a\PowerPlatformGithubActions\PowerPlatformGithubActions\MyDataversePackage.1.0.0.pdpkg.zip'
