name: Pack and deploy solution
run-name: Pack solution and deploy it managed to an environment
on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://[your-env].crm.dynamics.com"
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: yoursolutionname
env:
#edit your values here
  TENANT_ID: '67266d43-8de7-494d-9ed8-3d1bd3b3a764'
  CLIENT_ID: '4880a9e8-fd3c-4b89-9966-dc59b1e09984'
permissions:
  contents: write
jobs:
  pack-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - if: ${{ false }} # this will never run, but will force powerplatform-actions to download
        name: Who Am I
        uses: microsoft/powerplatform-actions/who-am-i@latest
        with:
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
          tenant-id: ${{env.TENANT_ID}}
          environment-url: ${{ github.event.inputs.environment_url}}

      # We need to use pac directly.
      # So we set the path to pac that ships with the Actions

      - uses: actions/checkout@v2
        with:
          lfs: true
            
      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}
          solution-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
          solution-type: Managed

      - name: Import solution as managed to env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
            environment-url: ${{ github.event.inputs.environment_url}}
            app-id: ${{ env.CLIENT_ID }}
            client-secret: ${{ secrets.POWER_PLATFORM_ACTIONS_APPUSER_SECRET }}
            tenant-id: ${{env.TENANT_ID}}
            solution-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
            force-overwrite: true
            publish-changes: false
